# Generated by Django 4.2.11 on 2025-01-24 10:06

import Employees.validators
from django.db import migrations, models
import django.db.models.deletion
import VBworkspace.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(db_column='employee_last_name', help_text='Введіть прізвище працівника', max_length=200, validators=[Employees.validators.validator_name], verbose_name='прізвище')),
                ('first_name', models.CharField(db_column='employee_first_name', help_text="Введіть ім'я працівника", max_length=200, validators=[Employees.validators.validator_name], verbose_name="ім'я")),
                ('patronymic', models.CharField(db_column='employee_patronymic', help_text='Введіть по-батькові працівника', max_length=200, validators=[Employees.validators.validator_name], verbose_name='по-батькові')),
                ('full_name', models.CharField(db_column='employee_full_name', editable=False, max_length=500, unique=True, verbose_name='ПІБ')),
                ('gender', models.CharField(choices=[('чоловіча', 'чоловіча'), ('жіноча', 'жіноча')], db_column='employee_gender', default='Не визначено', help_text='Оберіть стать працівника', max_length=10, verbose_name='стать')),
                ('birth_date', models.DateField(blank=True, db_column='employee_birth_date', help_text='Оберіть дату народження працівника', validators=[VBworkspace.validators.validator_birth_date], verbose_name='дата народження')),
                ('position', models.CharField(choices=[('Партнер', 'Партнер'), ('Радник', 'Радник'), ('Адвокат', 'Адвокат'), ('Юрист', 'Юрист'), ("Кур'єр", "Кур'єр"), ('Юридичний секретар', 'Юридичний секретар')], db_column='employee_position', help_text='Оберіть посаду, на якій перебуває працівник', max_length=100, verbose_name='посада')),
                ('foto', models.ImageField(db_column='employee_foto', help_text='Завантажте фото працівника', null=True, upload_to='Employees/templates/Employees/images/personal_foto/', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Досьє працівника',
                'verbose_name_plural': 'Досьє працівників',
                'db_table': 'EmployeeInfo',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeRewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.CharField(db_column='EmployeeRewards_reward', help_text='Оберіть нагороду/відзнаку працівника', max_length=500, verbose_name='нагорода/відзнака')),
                ('reward_auth', models.CharField(choices=[('Legal 500', 'Legal 500'), ('Who is Who Legal', 'Who is Who Legal'), ('Best Lawyers', 'Best Lawyers'), ('Юридична практика', 'Юридична практика'), ('Юридична газета', 'Юридична газета')], db_column='EmployeeRewards_reward_auth', help_text='Оберіть автора нагороди/відзнаки працівника', max_length=500, verbose_name='автор нагороди/відзнаки')),
                ('reward_year', models.IntegerField(choices=[(2025, '2025'), (2024, '2024'), (2023, '2023'), (2022, '2022'), (2021, '2021'), (2020, '2020'), (2019, '2019'), (2018, '2018'), (2017, '2017'), (2016, '2016'), (2015, '2015'), (2014, '2014'), (2013, '2013'), (2012, '2012'), (2011, '2011'), (2010, '2010'), (2009, '2009'), (2008, '2008'), (2007, '2007'), (2006, '2006'), (2005, '2005'), (2004, '2004'), (2003, '2003'), (2002, '2002'), (2001, '2001'), (2000, '2000'), (1999, '1999'), (1998, '1998'), (1997, '1997'), (1996, '1996'), (1995, '1995'), (1994, '1994'), (1993, '1993'), (1992, '1992'), (1991, '1991'), (1990, '1990'), (1989, '1989'), (1988, '1988'), (1987, '1987'), (1986, '1986'), (1985, '1985'), (1984, '1984'), (1983, '1983'), (1982, '1982'), (1981, '1981'), (1980, '1980'), (1979, '1979'), (1978, '1978'), (1977, '1977'), (1976, '1976'), (1975, '1975'), (1974, '1974'), (1973, '1973'), (1972, '1972'), (1971, '1971')], db_column='EmployeeRewards_reward_year', help_text='Оберіть рік отримання відзнаки/нагороди', verbose_name='рік отримання')),
                ('employee_name', models.ForeignKey(db_column='EmployeeRewards_employee_name', on_delete=django.db.models.deletion.CASCADE, to='Employees.employeesinfo', verbose_name='ПІБ працівника')),
            ],
            options={
                'verbose_name': 'Нагорода/відзнака',
                'verbose_name_plural': 'Нагороди/відзнаки',
                'db_table': 'EmployeeRewards',
                'ordering': ['reward_year'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(choices=[('Київ', (('Київський національний університет імені Тараса Шевченка', 'Київський національний університет імені Тараса Шевченка'), ('Київський національний економічний університет імені Вадима Гетьмана', 'Київський національний економічний університет імені Вадима Гетьмана'))), ('Харків', (('Національний юридичний університет імені Ярослава Мудрого', 'Національний юридичний університет імені Ярослава Мудрого'), ('Харківський національний університет імені В. Н. Каразіна', 'Харківський національний університет імені В. Н. Каразіна'))), ('Одеса', (('Національний університет «Одеська юридична академія', 'Національний університет «Одеська юридична академія'),)), ('Львів', (('Львівський національний університет імені Івана Франка', 'Львівський національний університет імені Івана Франка'),))], db_column='EmployeeEducation_university', help_text='Оберіть ВНЗ', max_length=300, verbose_name='Вищий навчальний заклад')),
                ('graduated_year', models.IntegerField(blank=True, choices=[(2025, '2025'), (2024, '2024'), (2023, '2023'), (2022, '2022'), (2021, '2021'), (2020, '2020'), (2019, '2019'), (2018, '2018'), (2017, '2017'), (2016, '2016'), (2015, '2015'), (2014, '2014'), (2013, '2013'), (2012, '2012'), (2011, '2011'), (2010, '2010'), (2009, '2009'), (2008, '2008'), (2007, '2007'), (2006, '2006'), (2005, '2005'), (2004, '2004'), (2003, '2003'), (2002, '2002'), (2001, '2001'), (2000, '2000'), (1999, '1999'), (1998, '1998'), (1997, '1997'), (1996, '1996'), (1995, '1995'), (1994, '1994'), (1993, '1993'), (1992, '1992'), (1991, '1991'), (1990, '1990'), (1989, '1989'), (1988, '1988'), (1987, '1987'), (1986, '1986'), (1985, '1985'), (1984, '1984'), (1983, '1983'), (1982, '1982'), (1981, '1981'), (1980, '1980'), (1979, '1979'), (1978, '1978'), (1977, '1977'), (1976, '1976'), (1975, '1975'), (1974, '1974'), (1973, '1973'), (1972, '1972'), (1971, '1971')], db_column='EmployeeEducation_graduated_year', help_text='Оберіть рік закінчення ВНЗ', verbose_name='Рік закінчення ВНЗ')),
                ('education_degree', models.CharField(choices=[('Молодший бакалавр', 'Молодший бакалавр'), ('Бакалавр', 'Бакалавр'), ('Спеціаліст', 'Спеціаліст'), ('Магістр', 'Магістр'), ('Доктор філософії', 'Доктор філософії'), ('Доктор Наук', 'Доктор Наук')], db_column='EmployeeEducation_education_degree', help_text='Оберіть освітній/науковий ступінь працівника', max_length=20, verbose_name='Освітній/науковий ступінь')),
                ('employee_name', models.ForeignKey(db_column='EmployeeEducation_employee_name', on_delete=django.db.models.deletion.CASCADE, to='Employees.employeesinfo', verbose_name='ПІБ працівника')),
            ],
            options={
                'verbose_name': 'Освіта',
                'verbose_name_plural': 'Освіта',
                'db_table': 'EmployeeEducation',
                'ordering': ['graduated_year'],
            },
        ),
        migrations.CreateModel(
            name='AttorneyLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_receipt', models.DateField(db_column='AttorneyLicense_date_receipt', help_text='Оберіть дату отримання Свідоцтва про право на зайняття адвокатською діяльністю', validators=[VBworkspace.validators.validator_birth_date], verbose_name='дата отримання Свідоцтва')),
                ('authority', models.CharField(choices=[('Діючі органи', (('Рада адвокатів Київської області', 'Рада адвокатів Київської області'), ('Рада адвокатів Одеської області', 'Рада адвокатів Одеської області'), ('Рада адвокатів Львівської області', 'Рада адвокатів Львівської області'), ('Рада адвокатів Харківської області', 'Рада адвокатів Харківської області')))], db_column='AttorneyLicense_authority', help_text='Оберіть орган адвокатського самоврядування, що видав Свідоцтво про право на зайняття адвокатською діяльністю', max_length=500, verbose_name='орган видачі')),
                ('serial', models.CharField(db_column='AttorneyLicense_serial', help_text='Введіть серію Свідоцтва про право на зайняття адвокатською діяльністю в форматі: АА', max_length=4, validators=[Employees.validators.validator_license_serial], verbose_name='серія Свідоцтва')),
                ('number', models.CharField(db_column='AttorneyLicense_number', help_text='Введіть № Свідоцтва про право на зайняття адвокатською діяльністю в форматі: 123456', max_length=10, validators=[Employees.validators.validator_license_number], verbose_name='№ Свідоцтва')),
                ('attorney_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employeesinfo')),
            ],
            options={
                'verbose_name': 'Свідоцтво про право на зайняття адвокатською діяльністю',
                'verbose_name_plural': 'Свідоцтва про право на зайняття адвокатською діяльністю',
                'db_table': 'AttorneyLicense',
                'ordering': ['attorney_name'],
            },
        ),
    ]
