# Generated by Django 4.2.11 on 2025-01-24 10:35

import Employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesinfo',
            name='slug_name',
            field=models.SlugField(default='None'),
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='foto',
            field=models.ImageField(db_column='employee_foto', help_text='Завантажте фото працівника', null=True, upload_to=Employees.models.EmployeesInfo.renamed_foto_location, verbose_name='фото'),
        ),
    ]
