# Generated by Django 4.2.11 on 2025-01-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_employeesinfo_slug_name_alter_employeesinfo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesinfo',
            name='slug_name',
            field=models.SlugField(default='None', editable=False),
        ),
    ]
