# Generated by Django 4.2.11 on 2025-01-29 12:12

import Employees.validators
from django.db import migrations, models
import django.db.models.deletion
import VBworkspace.validators

class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0003_alter_employeesinfo_slug_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesinfo',
            name='slug_name',
        ),
        migrations.CreateModel(
            name='EmployeePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.IntegerField(blank=True, db_column='phone_number', help_text='Введіть телефонний номер працівника', validators=[VBworkspace.validators.validator_birth_date], verbose_name='телефонний номер')),
                ('employee_name', models.ForeignKey(db_column='employee_name', on_delete=django.db.models.deletion.CASCADE, to='Employees.employeesinfo')),
            ],
            options={
                'verbose_name': 'Телефонний номер',
                'verbose_name_plural': 'Телефонні номери',
                'db_table': 'EmployeePhone',
            },
        ),
        migrations.CreateModel(
            name='EmployeeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_column='email', help_text='Введіть робочу електронну пошту працівника', max_length=254, verbose_name='електронна пошта')),
                ('employee_name', models.ForeignKey(db_column='employee_name', on_delete=django.db.models.deletion.CASCADE, to='Employees.employeesinfo')),
            ],
            options={
                'verbose_name': 'Електронна адреса',
                'verbose_name_plural': 'Електронні адреси',
                'db_table': 'EmployeeEmail',
            },
        ),
    ]
