# Generated by Django 4.2.11 on 2025-01-29 12:17

import Employees.validators
from django.db import migrations, models
import VBworkspace.validators


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0004_remove_employeesinfo_slug_name_employeephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeephone',
            name='email',
            field=models.CharField(blank=True, db_column='phone_number', help_text='Введіть телефонний номер працівника', max_length=12, validators=[VBworkspace.validators.validator_birth_date], verbose_name='телефонний номер'),
        ),
    ]
