# Generated by Django 4.2.11 on 2025-01-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0005_alter_employeephone_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeephone',
            old_name='email',
            new_name='phone',
        ),
    ]
