# Generated by Django 4.2.11 on 2025-01-29 13:28

import Employees.validators
from django.db import migrations, models
import VBworkspace.validators


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0006_rename_email_employeephone_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeephone',
            name='phone',
            field=models.CharField(blank=True, db_column='phone_number', help_text='Введіть телефонний номер працівника', max_length=13, validators=[VBworkspace.validators.validator_birth_date], verbose_name='телефонний номер'),
        ),
    ]
