# Generated by Django 4.2.11 on 2025-01-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0007_alter_employeephone_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesinfo',
            name='other_info',
            field=models.TextField(blank=True),
        ),
    ]
