# Generated by Django 4.2.11 on 2025-02-11 09:37

import VBworkspace.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0009_alter_attorneylicense_attorney_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeeducation',
            options={'ordering': ['employee_name', 'graduated_year'], 'verbose_name': 'Освіта', 'verbose_name_plural': 'Освіта'},
        ),
        migrations.AlterModelOptions(
            name='employeerewards',
            options={'ordering': ['employee_name', 'reward_year'], 'verbose_name': 'Нагорода/відзнака', 'verbose_name_plural': 'Нагороди/відзнаки'},
        ),
        migrations.AlterField(
            model_name='employeephone',
            name='phone',
            field=models.CharField(blank=True, db_column='phone_number', help_text='Введіть телефонний номер працівника', max_length=13, validators=[VBworkspace.validators.validator_phone], verbose_name='телефонний номер'),
        ),
    ]
