# Generated by Django 4.2.11 on 2025-02-11 09:37

import Clients.models
import VBworkspace.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employees', '0010_alter_employeeeducation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(db_column='client_name', help_text='Введіть ПІБ (для ФО) або найменування (для ЮО) клієнта', max_length=400, verbose_name='назва клієнта')),
                ('client_taxID', models.IntegerField(blank=True, db_column='client_taxID', help_text='Введіть РКНОПП (для ФО) або ЄДРПОУ (для ЮО) клієнта', unique=True, verbose_name='реєстраційний номер клієнта клієнта')),
                ('client_legal_address', models.CharField(db_column='client_legal_address', help_text='Введіть юридичну адресу клієнта (в форматі, що допустимий для процесуальних документів)', max_length=500, verbose_name='юридична адреса клієнта')),
                ('client_postal_address', models.CharField(db_column='client_postal_address', help_text='Введіть поштову адресу клієнта (в форматі, що допустимий для процесуальних документів)', max_length=500, verbose_name='поштова адреса клієнта')),
                ('client_foto', models.ImageField(db_column='client_foto', help_text='Завантажте фото клієнта (світлина, логотип, тощо)', null=True, upload_to=Clients.models.ClientsInfo.renamed_foto_location, verbose_name='фото клієнта')),
                ('client_other_info', models.TextField(blank=True, db_column='client_other_info', verbose_name='Додаткова інформація про клієнта')),
                ('client_responsible_employee', models.ForeignKey(db_column='client_responsible_employee', on_delete=django.db.models.deletion.PROTECT, to='Employees.employeesinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, db_column='client_phone', help_text='Введіть телефонний номер клієнта', max_length=13, validators=[VBworkspace.validators.validator_phone], verbose_name='телефонний номер')),
                ('client_id', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='Clients.clientsinfo')),
            ],
            options={
                'verbose_name': 'Телефонний номер',
                'verbose_name_plural': 'Телефонні номери',
                'db_table': 'ClientPhone',
            },
        ),
        migrations.CreateModel(
            name='ClientEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.CharField(db_column='client_email', help_text='Введіть email клієнта', max_length=100, verbose_name='email клієнта')),
                ('client_id', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='Clients.clientsinfo')),
            ],
            options={
                'verbose_name': 'Email клієнта',
                'verbose_name_plural': 'Перелік email Клієнта',
                'db_table': 'ClientEmail',
            },
        ),
        migrations.CreateModel(
            name='ClientDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_date', models.DateField(db_column='client_date', help_text='Оберіть дату', validators=[VBworkspace.validators.validator_birth_date], verbose_name='важлива дата клієнта')),
                ('client_date_description', models.CharField(db_column='client_date_description', max_length=500, verbose_name='Опис важливої дати клієнта')),
                ('client_id', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='Clients.clientsinfo')),
            ],
            options={
                'verbose_name': 'Важлива дата клієнта',
                'verbose_name_plural': 'Важливі дати клієнта',
                'db_table': 'ClientDates',
            },
        ),
        migrations.CreateModel(
            name='ClientActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_activities', models.CharField(choices=[('Банкінг', 'Банкінг'), ('Гемблінг', 'Гемблінг'), ('Видобуток копалин', 'Видобуток копалин'), ('Металургія', 'Металургія')], db_column='client_activities', help_text='Оберіть бізнес активність клієнта', max_length=100, verbose_name='бізнес активність клієнта')),
                ('client_id', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='Clients.clientsinfo')),
            ],
            options={
                'verbose_name': 'Бізнес-активність клієнта',
                'verbose_name_plural': 'Бізнес-активності Клієнта',
                'db_table': 'ClientActivities',
            },
        ),
    ]
