# Generated by Django 4.2.11 on 2025-02-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_alter_clientsinfo_options_alter_clientsinfo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdates',
            name='client_date_description',
            field=models.TextField(db_column='client_date_description', max_length=500, verbose_name='Опис важливої дати клієнта'),
        ),
        migrations.AlterField(
            model_name='clientsinfo',
            name='client_legal_address',
            field=models.TextField(db_column='client_legal_address', help_text='Введіть юридичну адресу клієнта (в форматі, що допустимий для процесуальних документів)', max_length=500, verbose_name='юридична адреса клієнта'),
        ),
        migrations.AlterField(
            model_name='clientsinfo',
            name='client_postal_address',
            field=models.TextField(db_column='client_postal_address', help_text='Введіть поштову адресу клієнта (в форматі, що допустимий для процесуальних документів)', max_length=500, verbose_name='поштова адреса клієнта'),
        ),
    ]
