# Generated by Django 4.2.11 on 2025-02-11 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0010_alter_employeeeducation_options_and_more'),
        ('Clients', '0003_alter_clientdates_client_date_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsinfo',
            name='client_responsible_employee',
            field=models.ForeignKey(db_column='client_responsible_employee', on_delete=django.db.models.deletion.PROTECT, to='Employees.employeesinfo', verbose_name='відповідальний працівник'),
        ),
        migrations.AlterField(
            model_name='clientsinfo',
            name='client_taxID',
            field=models.CharField(blank=True, db_column='client_taxID', help_text='Введіть РКНОПП (для ФО) або ЄДРПОУ (для ЮО) клієнта', max_length=15, unique=True, verbose_name='реєстраційний номер клієнта клієнта'),
        ),
        migrations.CreateModel(
            name='ClientManagers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_manager_name', models.CharField(db_column='client_manager_name', help_text='Введіть ПІБ менеджера клієнта', max_length=400, verbose_name='ПІБ менеджера клієнта')),
                ('client_manager_role', models.TextField(db_column=' client_manager_role', help_text='Введіть статус/повноваження менеджера клієнта', max_length=400, verbose_name='статус/повноваження менеджера клієнта')),
                ('client_id', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='Clients.clientsinfo')),
            ],
            options={
                'verbose_name': 'Менеджер клієнта',
                'verbose_name_plural': 'Менеджери клієнта',
                'db_table': 'ClientManagers',
            },
        ),
    ]
