# Generated by Django 4.2.11 on 2025-02-11 12:08

import VBworkspace.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0004_alter_clientsinfo_client_responsible_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmanagers',
            name='client_manager_email',
            field=models.CharField(blank=True, db_column='client_manager_email', help_text='Введіть email менеджера клієнта', max_length=100, verbose_name='email менеджера клієнта'),
        ),
        migrations.AddField(
            model_name='clientmanagers',
            name='client_manager_other_info',
            field=models.TextField(blank=True, db_column='client_manager_other_info', verbose_name='Додаткова інформація про менеджера клієнта'),
        ),
        migrations.AddField(
            model_name='clientmanagers',
            name='client_manager_phone',
            field=models.CharField(blank=True, db_column='client_manager_phone', help_text='Введіть телефонний номер менеджера клієнта', max_length=13, validators=[VBworkspace.validators.validator_phone], verbose_name='телефонний номер менеджера клієнта'),
        ),
        migrations.AlterField(
            model_name='clientmanagers',
            name='client_manager_role',
            field=models.CharField(db_column=' client_manager_role', help_text='Введіть статус/повноваження менеджера клієнта', max_length=400, verbose_name='статус/повноваження менеджера клієнта'),
        ),
        migrations.AlterField(
            model_name='clientphone',
            name='phone',
            field=models.CharField(blank=True, db_column='client_phone', help_text='Введіть телефонний номер клієнта', max_length=13, validators=[VBworkspace.validators.validator_phone], verbose_name='телефонний номер менеджера'),
        ),
        migrations.AlterField(
            model_name='clientsinfo',
            name='client_legal_address',
            field=models.CharField(db_column='client_legal_address', help_text='Введіть юридичну адресу клієнта (в форматі, що допустимий для процесуальних документів)', max_length=500, verbose_name='юридична адреса клієнта'),
        ),
        migrations.AlterField(
            model_name='clientsinfo',
            name='client_postal_address',
            field=models.CharField(db_column='client_postal_address', help_text='Введіть поштову адресу клієнта (в форматі, що допустимий для процесуальних документів)', max_length=500, verbose_name='поштова адреса клієнта'),
        ),
    ]
