# Generated by Django 4.2.11 on 2025-02-19 07:24

import Clients.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0006_alter_clientsinfo_client_foto_clientagreements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientagreements',
            name='client_agreement_description',
            field=models.TextField(blank=True, db_column='client_agreement_description', help_text='Додайте опис суті договору', max_length=500, verbose_name='Опис суті договору з клієнтом'),
        ),
        migrations.AlterField(
            model_name='clientagreements',
            name='client_agreement_file',
            field=models.FileField(blank=True, db_column='client_agreement_file', help_text='Додайте файл з договором в форматі PDF', upload_to=Clients.models.ClientAgreements.renamed_file_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='файл договору з клієнтом'),
        ),
    ]
