# Generated by Django 4.2.11 on 2025-02-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0010_alter_clientagreements_client_agreement_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientagreements',
            name='client_agreement_representative_name',
            field=models.CharField(blank=True, db_column='client_agreement_representative_name', help_text='Введіть ПІБ представника клієнта, що підписав договір', max_length=400, verbose_name='ПІБ представника клієнта, що підписав договір'),
        ),
        migrations.AddField(
            model_name='clientagreements',
            name='client_agreement_representative_position',
            field=models.CharField(blank=True, db_column='client_agreement_representative_position', help_text='Введіть посаду представника клієнта, що підписав договір (або дані довіреності)', max_length=200, verbose_name='посада представника клієнта, що підписав договір (або дані довіреності)'),
        ),
        migrations.AlterField(
            model_name='clientagreements',
            name='client_agreement_description',
            field=models.TextField(blank=True, db_column='client_agreement_description', help_text='Додайте опис суті договору', max_length=1000, verbose_name='Опис суті договору з клієнтом'),
        ),
    ]
