# Generated by Django 4.2.11 on 2025-02-19 13:32

import Clients.models
import VBworkspace.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0011_clientagreements_client_agreement_representative_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAdditionalAgreements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_additional_agreement_number', models.CharField(db_column='client_additional_agreement_number', help_text='Введіть номер додаткової угоди до договору або б/н', max_length=50, unique=True, verbose_name='номер додаткової угоди до договору з клієнтом')),
                ('client_additional_agreement_date', models.DateField(db_column='client_additional_agreement_date', help_text='Оберіть дату укладення додаткової угоди до договору', validators=[VBworkspace.validators.validator_birth_date], verbose_name='дата укладення додаткової угоди до договору з клієнтом')),
                ('client_additional_agreement_description', models.TextField(blank=True, db_column='client_additional_agreement_description', help_text='Додайте опис суті додаткової угоди до договору', max_length=1000, verbose_name='Опис суті додаткової угоди до договору з клієнтом')),
                ('client_additional_agreement_representative_name', models.CharField(blank=True, db_column='client_additional_agreement_representative_name', help_text='Введіть ПІБ представника клієнта, що підписав додаткову угоду до договору', max_length=400, verbose_name='ПІБ представника клієнта, що підписав додаткову угоду до договору')),
                ('client_additional_agreement_representative_position', models.CharField(blank=True, db_column='client_additional_agreement_representative_position', help_text='Введіть посаду представника клієнта, що підписав додаткову угоду до договору (або дані довіреності)', max_length=200, verbose_name='посада представника клієнта, що підписав додаткову угоду до договору (або дані довіреності)')),
                ('client_additional_agreement_file', models.FileField(blank=True, db_column='client_additional_agreement_file', default='/../../media/Clients/files/agreements/default.pdf', help_text='Додайте файл додаткової угоди до договору в форматі PDF', upload_to=Clients.models.ClientAdditionalAgreements.renamed_file_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='файл додаткової угоди до договору з клієнтом (pdf)')),
                ('agreement_id', models.ForeignKey(db_column='agreement_id', on_delete=django.db.models.deletion.CASCADE, to='Clients.clientsinfo')),
            ],
            options={
                'verbose_name': 'Додаткова угода до Договору з клієнтом',
                'verbose_name_plural': 'Додаткові угоди до Договору з клієнтом',
                'db_table': 'ClientAdditionalAgreements',
            },
        ),
    ]
