# Generated by Django 4.2.11 on 2025-02-19 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0012_clientadditionalagreements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientagreements',
            options={'verbose_name': 'Договір з Клієнтом', 'verbose_name_plural': 'Договори з Клієнтами'},
        ),
        migrations.AlterField(
            model_name='clientadditionalagreements',
            name='agreement_id',
            field=models.ForeignKey(db_column='agreement_id', on_delete=django.db.models.deletion.CASCADE, to='Clients.clientagreements'),
        ),
        migrations.AlterField(
            model_name='clientagreements',
            name='client_id',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='Clients.clientsinfo', verbose_name='Клієнт'),
        ),
    ]
