# Generated by Django 4.2.11 on 2025-02-19 15:46

import Clients.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0013_alter_clientagreements_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientadditionalagreements',
            name='client_additional_agreement_file',
            field=models.FileField(blank=True, db_column='client_additional_agreement_file', default='/../../media/Clients/files/agreements/default.pdf', help_text='Додайте файл додаткової угоди до договору в форматі PDF', null='/../../media/Clients/files/agreements/default.pdf', upload_to=Clients.models.ClientAdditionalAgreements.renamed_file_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='файл додаткової угоди до договору з клієнтом (pdf)'),
        ),
        migrations.AlterField(
            model_name='clientagreements',
            name='client_agreement_file',
            field=models.FileField(blank=True, db_column='client_agreement_file', default='/../../media/Clients/files/agreements/default.pdf', help_text='Додайте файл з договором в форматі PDF', null='/../../media/Clients/files/agreements/default.pdf', upload_to=Clients.models.ClientAgreements.renamed_file_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='файл договору з клієнтом (pdf)'),
        ),
    ]
